DROP table IF EXISTS PUBLIC."departments" CASCADE;
DROP table IF EXISTS PUBLIC."employees" CASCADE;

CREATE TABLE IF NOT EXISTS PUBLIC."departments"
(
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS PUBLIC."employees"
(
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "first_name"      VARCHAR(255) NOT NULL,
    "last_name"       VARCHAR(255) NOT NULL,
    "position"       VARCHAR(100) NOT NULL,
    "salary"        VARCHAR(100) NOT NULL,
    "departments_id" BIGINT       NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT fk_departments FOREIGN KEY (departments_id) REFERENCES departments (id)
);

MERGE INTO PUBLIC."departments" values (1, 'aaaa');
MERGE INTO PUBLIC."departments" values (2, 'bbbbb');
MERGE INTO PUBLIC."departments" values (3, 'cccccc');
MERGE INTO PUBLIC."departments" values (4, 'dddddd');
